# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: MIT

# https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: 'pip'
    directories:
      - '.github/workflows'
    schedule:
      interval: 'monthly'
    cooldown:
      default-days: 7
      semver-major-days: 15
      semver-minor-days: 7
      semver-patch-days: 3
