# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: curl

# https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'quarterly'
    cooldown:
      default-days: 30
    groups:
      actions-deps:
        patterns:
          - '*'

  - package-ecosystem: 'pip'
    directories:
      - '.github/workflows'
    schedule:
      interval: 'quarterly'
    cooldown:
      default-days: 7
      semver-major-days: 15
      semver-minor-days: 7
      semver-patch-days: 3
