# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: curl
---
name: curl-for-win

'on':
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions: {}

env:
  CW_GET: 'curl'
  CW_MAP: '0'
  CW_JOBS: '5'
  CW_PKG_NODELETE: '1'
  CW_PKG_FLATTEN: '1'

jobs:
  win-llvm:
    name: 'Windows llvm (ARM64, x64)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          path: 'trurl'
          fetch-depth: 8
      - name: 'build'
        env:
          CW_LLVM_MINGW_DL: '1'
          CW_LLVM_MINGW_ONLY: '0'
          CW_TURL_TEST: '1'
        run: |
          git clone --depth 1 https://github.com/curl/curl-for-win
          mv curl-for-win/* .
          export CW_CONFIG='-dev-zero-imap-osnotls-osnoidn-nohttp-nocurltool-win'
          export CW_REVISION="${GITHUB_SHA}"
          . ./_versions.sh
          sudo podman image trust set --type reject default
          sudo podman image trust set --type accept docker.io/library
          time podman pull "${OCI_IMAGE_DEBIAN}"
          time podman run --volume "$(pwd):$(pwd)" --workdir "$(pwd)" \
            --env-file <(env | grep -a -E \
              '^(CW_|GITHUB_)') \
            "${OCI_IMAGE_DEBIAN}" \
            sh -c ./_ci-linux-debian.sh

      - name: 'list dependencies'
        run: cat urls.txt
      - uses: actions/upload-artifact@v4
        with:
          name: 'trurl-windows'
          retention-days: 5
          path: curl-*-*-*/trurl*
