# Copyright (C) Viktor Szakats. See LICENSE.md
# SPDX-License-Identifier: curl
---
name: curl-for-win

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

env:
  CW_GET: 'curl'
  CW_BLD: 'trurl'  # to save time by not building a default curl
  CW_MAP: '0'
  CW_JOBS: '5'
  CW_TRURL_TEST: '1'
  CW_NOPKG: '1'

jobs:
  win-llvm:
    name: 'Windows llvm (x64)'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          path: 'trurl'
          fetch-depth: 8
      - name: 'build'
        env:
          CW_LLVM_MINGW_DL: '1'
          CW_LLVM_MINGW_ONLY: '0'
        run: |
          git clone --depth 1 https://github.com/curl/curl-for-win
          mv curl-for-win/* .
          export CW_CONFIG='-dev-zero-win-x64'  # use '-zero' to avoid 3rd-party dependencies
          export CW_REVISION="${GITHUB_SHA}"
          . ./_versions.sh
          sudo podman image trust set --type reject default
          sudo podman image trust set --type accept docker.io/library
          time podman pull "${OCI_IMAGE_DEBIAN}"
          time podman run --volume "$(pwd):$(pwd)" --workdir "$(pwd)" \
            --env-file <(env | grep -a -E \
              '^(CW_|GITHUB_)') \
            "${OCI_IMAGE_DEBIAN}" \
            sh -c ./_ci-linux-debian.sh

      - name: 'list dependencies'
        run: cat urls.txt

  linux-glibc-gcc-minimal:  # use gcc to minimize installed packages
    name: 'Linux gcc glibc minimal'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
          path: 'trurl'
          fetch-depth: 8
      - name: 'build'
        run: |
          git clone --depth 1 https://github.com/curl/curl-for-win
          mv curl-for-win/* .
          export CW_CONFIG='-dev-zero-imap-osnotls-osnoidn-nohttp-noverbose-nocurltool-linux-x64-gcc'
          export CW_REVISION="${GITHUB_SHA}"
          . ./_versions.sh
          sudo podman image trust set --type reject default
          sudo podman image trust set --type accept docker.io/library
          time podman pull "${OCI_IMAGE_DEBIAN}"
          time podman run --volume "$(pwd):$(pwd)" --workdir "$(pwd)" \
            --env-file <(env | grep -a -E \
              '^(CW_|GITHUB_)') \
            "${OCI_IMAGE_DEBIAN}" \
            sh -c ./_ci-linux-debian.sh
