name: build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build:
          - name: default
            install_packages: valgrind
            test: test-memory
          - name: clang sanitizers
            install_packages: clang
            test: test
            make_opts: >
              CC=clang
              CFLAGS="-fsanitize=address,undefined,signed-integer-overflow -Wformat -Werror=format-security -Werror=array-bounds -g"
              LDFLAGS="-fsanitize=address,undefined,signed-integer-overflow -g"

    steps:
      - uses: actions/checkout@v3

      - name: install libcurl
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev ${{ matrix.build.install_packages }}

      - name: code style check
        run: make checksrc

      - name: make
        run: make ${{ matrix.build.make_opts }}

      - name: sanity test
        run: ./trurl -v

      - name: test
        run: make ${{matrix.build.test}}

  cygwin:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: install cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: curl, libcurl-devel, libcurl4, make, gcc-core, python39

      - name: make
        run: make

      - name: sanity test
        run: ./trurl -v

      - name: test
        run: make test

  macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: make
        run: make

      - name: sanity test
        run: ./trurl -v

      - name: test
        run: make test
